<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_2024_dncalendar-next-month</name>
   <tag></tag>
   <elementGuidId>3d63db0f-3535-4a63-8e1b-e587ef551a95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dncalendar-next-month']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dncalendar-next-month</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#dncalendar-next-month</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>89b6712c-0567-439c-bd9d-09f5946d6932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dncalendar-next-month</value>
      <webElementGuid>ab023f19-a757-43fa-b873-2a5d8e0684f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dncalendar-next-month</value>
      <webElementGuid>e96bcac7-8abb-45c2-afc5-f9b63d7d13a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dncalendar-next-month&quot;)</value>
      <webElementGuid>be5140d7-1426-4e5e-a593-bd4acbb6ac23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dncalendar-next-month']</value>
      <webElementGuid>8ba0434d-5e08-4d4f-a12d-c51e15ed811e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dncalendar-links']/div[2]</value>
      <webElementGuid>b6a6826f-d0f3-4532-b83a-ae605914f56c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4/div/div/div[2]</value>
      <webElementGuid>8551321c-c483-4231-a3c1-1e87769947a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dncalendar-next-month']</value>
      <webElementGuid>f76a5e8a-a249-4617-88d4-ae7495ebdbed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
