<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Gallery_lightbox</name>
   <tag></tag>
   <elementGuidId>641250ec-624d-4955-bcf8-1951791df7c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Gallery'])[2]/following::a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(2) > .lightbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b8aa16c0-dfe2-4912-8412-caf2f3ce4e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lightbox</value>
      <webElementGuid>720dafa3-be20-4284-9bd2-f6bdfff516c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>gallery/2.jpg</value>
      <webElementGuid>22263668-c710-4fa5-a1d8-a1708bacb3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;font-inc-dec&quot;]/div[@class=&quot;top-blue-strip&quot;]/div[@class=&quot;container gallery-container&quot;]/div[@class=&quot;tz-gallery&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-md-3&quot;]/a[@class=&quot;lightbox&quot;]</value>
      <webElementGuid>6a75e0d5-d823-41f0-adad-7dcde9d72645</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gallery'])[2]/following::a[2]</value>
      <webElementGuid>af73ebcb-0a52-4ca1-89be-1d29317f5dde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download I.P.A.S.E Theory Hall Tickets May 2024'])[1]/following::a[2]</value>
      <webElementGuid>3e689d9a-dcdf-40c7-a501-cd4c4d031412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get in Touch'])[1]/preceding::a[19]</value>
      <webElementGuid>91b7be78-8b68-4918-80ff-c7e9f9fd073b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow Us'])[2]/preceding::a[19]</value>
      <webElementGuid>b75758fd-2e99-4219-8ec9-c3c871865ed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'gallery/2.jpg')]</value>
      <webElementGuid>e7d4701c-62de-4fb6-8195-f40acea5ccb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/a</value>
      <webElementGuid>d0e553d9-1e25-4936-b464-0b69145c314c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'gallery/2.jpg']</value>
      <webElementGuid>8a8813c6-c91e-4796-a7d1-19295f1deb34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
